name: Verify changes on feature branches

on:
  push:
    branches-ignore:
      - master
      - main
      - develop
      - 'develop-*'

jobs:
  test:
    name: Test python package
    uses: ./.github/workflows/python-test.yml

  docker:
    name: Create and test Docker images
    uses: ./.github/workflows/docker.yml
    needs: test
    with:
      release: false
      push: false
    secrets: inherit

